services:
  webserver:
    build:
      context: .
    image: oficina_lmc
    container_name: "projeto_final"
    links: 
    - mysql
    depends_on: 
    - mysql
    volumes: 
    - .:/home/node/app
    ports:
      - "5001:5001"
    environment: 
    - MYSQL_PASS=123
    networks: 
    - app-web-net

  mysql:
    image: mysql:latest
    container_name: "mysql"
    restart: "always"
    ports:
      - "3306:3306"
    environment:
     - MYSQL_ROOT_PASSWORD=123
    networks: 
    - app-web-net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: "phpmyadmin"
    links: 
    - mysql
    depends_on: 
    - mysql
    ports:
      - "5001:5001"
    volumes: 
    - /sessions
    environment: 
    - PMA_HOST=mysql 
    - PMA_PORT=5001
    networks: 
    - app-web-net

networks:
  app-web-net:
